version: '3'
services: 
    database:
        image: 'mongo'
        container_name: 'db-mongo'
        environment: 
            - MONGO_INITDB_DATABASE=myDatabase
            - MONGO_INITDB_ROOT_USERNAME=myUser
            - MONGO_INITDB_ROOT_PASSWORD=myPass
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo-volumes/:/data/db
        ports: 
            - '27017-27019:27017-27019'